spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:huntjob"

server:
  address: 0.0.0.0
  port: 7070

