spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:huntjob"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

server:
  address: 0.0.0.0
  port: 7070

